import fs from 'node:fs';
import path from 'node:path';
import childProcess from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const SHELL_ROOT = path.resolve(__dirname, '..');
const WORKSPACE = path.resolve(SHELL_ROOT, '..', '..');
const STATE = path.join(WORKSPACE, 'state');
const STATUS_OUT = path.join(STATE, 'desktop_electron_autostart_control_status.json');
const AUDIT_OUT = path.join(STATE, 'desktop_electron_autostart_control_audit.jsonl');
const TASK_NAME = 'Local Evolution Agent Desktop Companion Tray';
const STARTUP_DIR = process.platform === 'win32' && process.env.APPDATA
  ? path.join(process.env.APPDATA, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup')
  : null;
const STARTUP_CMD = STARTUP_DIR ? path.join(STARTUP_DIR, `${TASK_NAME}.cmd`) : null;
const ELECTRON_EXE = process.platform === 'win32'
  ? path.join(SHELL_ROOT, 'node_modules', 'electron', 'dist', 'electron.exe')
  : path.join(SHELL_ROOT, 'node_modules', '.bin', 'electron');
const DASHBOARD = path.join(STATE, 'app_shell_dashboard.html');
const APP_MAIN = path.join(SHELL_ROOT, 'src', 'main.js');
const LAUNCH_TARGET = `"${ELECTRON_EXE}" "${SHELL_ROOT}"`;

function runSchtasks(args) {
  if (process.platform !== 'win32') {
    return { supported: false, status: null, rc: null, stdout: '', stderr: 'unsupported-platform', error: null };
  }
  const result = childProcess.spawnSync('schtasks.exe', args, {
    encoding: 'utf8',
    windowsHide: true,
    timeout: 15000,
  });
  return {
    supported: true,
    status: result.status,
    rc: result.status,
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
    error: result.error ? `${result.error.name}: ${result.error.message}` : null,
  };
}

function queryTask() {
  const result = runSchtasks(['/Query', '/TN', TASK_NAME, '/FO', 'LIST']);
  return {
    installed: result.status === 0,
    status: result.status === 0 ? 'installed' : 'not-installed',
    rc: result.status,
    supported: result.supported,
    error: result.error,
    stdoutTail: result.stdout.slice(-2000),
    stderrTail: result.stderr.slice(-2000),
  };
}

function queryStartupCmd() {
  const exists = Boolean(STARTUP_CMD && fs.existsSync(STARTUP_CMD));
  let contentMatches = false;
  let contentPreview = '';
  if (exists) {
    try {
      contentPreview = fs.readFileSync(STARTUP_CMD, 'utf8').slice(0, 500);
      contentMatches = contentPreview.includes(ELECTRON_EXE) && contentPreview.includes(SHELL_ROOT);
    } catch {}
  }
  return {
    supported: Boolean(STARTUP_CMD),
    installed: exists && contentMatches,
    exists,
    contentMatches,
    path: STARTUP_CMD,
    contentPreview,
  };
}

function writeStartupCmd() {
  if (!STARTUP_CMD || !STARTUP_DIR) return { attempted: false, reason: 'startup-folder-unavailable' };
  fs.mkdirSync(STARTUP_DIR, { recursive: true });
  const content = [
    '@echo off',
    'REM Local Evolution Agent Desktop Companion Tray autostart. Generated by autostart-control.js; safe to delete.',
    `start "" "${ELECTRON_EXE}" "${SHELL_ROOT}"`,
    '',
  ].join('\r\n');
  fs.writeFileSync(STARTUP_CMD, content, 'utf8');
  return { attempted: true, path: STARTUP_CMD };
}

function deleteStartupCmd() {
  if (!STARTUP_CMD) return { attempted: false, reason: 'startup-folder-unavailable' };
  if (!fs.existsSync(STARTUP_CMD)) return { attempted: false, reason: 'startup-cmd-not-installed', path: STARTUP_CMD };
  fs.rmSync(STARTUP_CMD, { force: true });
  return { attempted: true, path: STARTUP_CMD };
}

function prereqGates() {
  return [
    { id: 'windows-scheduled-task-supported', passed: process.platform === 'win32', evidence: process.platform },
    { id: 'electron-exe-present', passed: fs.existsSync(ELECTRON_EXE), evidence: ELECTRON_EXE },
    { id: 'electron-app-main-present', passed: fs.existsSync(APP_MAIN), evidence: APP_MAIN },
    { id: 'dashboard-present', passed: fs.existsSync(DASHBOARD), evidence: DASHBOARD },
  ];
}

function installTask() {
  const before = queryTask();
  const startupBefore = queryStartupCmd();
  if (before.installed || startupBefore.installed) return { attempted: false, reason: 'already-installed', before, startupBefore, commandArgs: [] };
  const commandArgs = ['/Create', '/TN', TASK_NAME, '/TR', LAUNCH_TARGET, '/SC', 'ONLOGON', '/RL', 'LIMITED', '/F'];
  const raw = runSchtasks(commandArgs);
  const after = queryTask();
  let fallback = null;
  if (!after.installed) fallback = writeStartupCmd();
  const startupAfter = queryStartupCmd();
  return { attempted: true, before, startupBefore, raw: summarizeRaw(raw), after, fallback, startupAfter, commandArgs };
}

function uninstallTask() {
  const before = queryTask();
  const startupBefore = queryStartupCmd();
  if (!before.installed && !startupBefore.exists) return { attempted: false, reason: 'not-installed', before, startupBefore, commandArgs: [] };
  const commandArgs = ['/Delete', '/TN', TASK_NAME, '/F'];
  const raw = before.installed ? runSchtasks(commandArgs) : { supported: true, rc: 0, stdout: '', stderr: '', error: null };
  const startupDelete = deleteStartupCmd();
  const after = queryTask();
  const startupAfter = queryStartupCmd();
  return { attempted: true, before, startupBefore, raw: summarizeRaw(raw), startupDelete, after, startupAfter, commandArgs };
}

function summarizeRaw(raw) {
  return {
    supported: raw.supported,
    rc: raw.rc,
    error: raw.error,
    stdoutTail: raw.stdout.slice(-2000),
    stderrTail: raw.stderr.slice(-2000),
  };
}

function parseMode() {
  if (process.argv.includes('--install')) return 'install';
  if (process.argv.includes('--uninstall')) return 'uninstall';
  if (process.argv.includes('--status')) return 'status';
  return 'status';
}

function main() {
  fs.mkdirSync(STATE, { recursive: true });
  const mode = parseMode();
  const gates = prereqGates();
  const prereqsOk = gates.every((gate) => gate.passed);
  let action = { attempted: false, reason: 'status-only' };
  if (!prereqsOk && mode !== 'status') {
    action = { attempted: false, reason: 'blocked-prereq-failed' };
  } else if (mode === 'install') {
    action = installTask();
  } else if (mode === 'uninstall') {
    action = uninstallTask();
  }
  const task = queryTask();
  const startupCmd = queryStartupCmd();
  const commandPreview = {
    installArgs: ['/Create', '/TN', TASK_NAME, '/TR', LAUNCH_TARGET, '/SC', 'ONLOGON', '/RL', 'LIMITED', '/F'],
    uninstallArgs: ['/Delete', '/TN', TASK_NAME, '/F'],
    startupCmdPath: STARTUP_CMD,
    startupCmdContent: `start "" "${ELECTRON_EXE}" "${SHELL_ROOT}"`,
  };
  const installed = task.installed || startupCmd.installed;
  const ok = prereqsOk && (mode === 'status' || (mode === 'install' ? installed : !task.installed && !startupCmd.exists));
  const doc = {
    timestamp: new Date().toISOString(),
    status: ok ? 'ok' : 'blocked-or-failed',
    mode: `electron-autostart-control-${mode}`,
    taskName: TASK_NAME,
    launchTarget: LAUNCH_TARGET,
    task,
    startupCmd,
    installed,
    gates,
    action,
    commandPreview,
    safety: {
      reversible: true,
      rollbackCommandArgs: commandPreview.uninstallArgs,
      startsPersistentProcessNow: false,
      createsOnLogonAutostartOnly: mode === 'install' && installed,
      externalNetworkWrites: false,
      microphone: false,
      camera: false,
      realPhysicalActuation: false,
      mutationScope: 'Windows Scheduled Task or current-user Startup folder .cmd for on-logon Electron tray launch only',
    },
  };
  fs.writeFileSync(STATUS_OUT, `${JSON.stringify(doc, null, 2)}\n`, 'utf8');
  fs.appendFileSync(AUDIT_OUT, `${JSON.stringify({ timestamp: doc.timestamp, mode, status: doc.status, taskInstalled: task.installed, startupCmdInstalled: startupCmd.installed, installed, actionAttempted: action.attempted, launchTarget: LAUNCH_TARGET }, null, 0)}\n`, 'utf8');
  console.log(JSON.stringify({ ok: doc.status === 'ok', out: STATUS_OUT, status: doc.status, mode, taskInstalled: task.installed, startupCmdInstalled: startupCmd.installed, installed, actionAttempted: action.attempted }, null, 2));
}

main();
